#!/usr/bin/env python3
SCHEMA='''
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sites(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,site_key TEXT NOT NULL UNIQUE,domains_json TEXT NOT NULL DEFAULT '[]',enabled INTEGER NOT NULL DEFAULT 1,heatmap_enabled INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS pageviews(id INTEGER PRIMARY KEY AUTOINCREMENT,site_id INTEGER NOT NULL,ts INTEGER NOT NULL,visitor_id TEXT NOT NULL,session_id TEXT NOT NULL,path TEXT NOT NULL,title TEXT DEFAULT '',referrer TEXT DEFAULT '',source TEXT DEFAULT '',medium TEXT DEFAULT '',campaign TEXT DEFAULT '',content TEXT DEFAULT '',term TEXT DEFAULT '',browser TEXT DEFAULT '',os TEXT DEFAULT '',device TEXT DEFAULT '',screen TEXT DEFAULT '',language TEXT DEFAULT '',country TEXT DEFAULT '',FOREIGN KEY(site_id) REFERENCES sites(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,site_id INTEGER NOT NULL,session_id TEXT NOT NULL,visitor_id TEXT NOT NULL,first_seen INTEGER NOT NULL,last_seen INTEGER NOT NULL,entry_path TEXT NOT NULL,exit_path TEXT NOT NULL,pageviews INTEGER NOT NULL DEFAULT 1,source TEXT DEFAULT '',country TEXT DEFAULT '',browser TEXT DEFAULT '',os TEXT DEFAULT '',device TEXT DEFAULT '',UNIQUE(site_id,session_id),FOREIGN KEY(site_id) REFERENCES sites(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS vitals(id INTEGER PRIMARY KEY AUTOINCREMENT,site_id INTEGER NOT NULL,ts INTEGER NOT NULL,visitor_id TEXT NOT NULL,session_id TEXT NOT NULL,path TEXT NOT NULL,lcp REAL,cls REAL,inp REAL,fcp REAL,ttfb REAL,FOREIGN KEY(site_id) REFERENCES sites(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS clicks(id INTEGER PRIMARY KEY AUTOINCREMENT,site_id INTEGER NOT NULL,ts INTEGER NOT NULL,visitor_id TEXT NOT NULL,session_id TEXT NOT NULL,path TEXT NOT NULL,x REAL NOT NULL,y REAL NOT NULL,viewport_w INTEGER NOT NULL,viewport_h INTEGER NOT NULL,selector TEXT DEFAULT '',FOREIGN KEY(site_id) REFERENCES sites(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_pv_st ON pageviews(site_id,ts);
CREATE INDEX IF NOT EXISTS idx_ss_last ON sessions(site_id,last_seen);
CREATE INDEX IF NOT EXISTS idx_vitals_st ON vitals(site_id,ts);
CREATE INDEX IF NOT EXISTS idx_clicks_sp ON clicks(site_id,path,ts);
'''
